import type { Engine } from './types';

// Curated Estes-class engines. Values mirror the original RocketModeler applet
// (Test0014.java, Constants.initialize). Units: mm, mm, g, g, N, N, s, s, s.
export const ENGINES: Engine[] = [
  {
    id: 'half-A6-2',
    name: '1/2A6-2',
    manufacturer: 'Estes',
    classLetter: '1/2A',
    width: 13,
    length: 45,
    mass: 7.0,
    fuelMass: 2.0,
    avThrust1: 6,
    avThrust2: 0,
    burnTime1: 0.2,
    totalBurnTime: 0.21,
    delayTime: 2.0,
    isBooster: false,
  },
  {
    id: 'A8-0',
    name: 'A8-0',
    manufacturer: 'Estes',
    classLetter: 'A',
    width: 18,
    length: 70,
    mass: 16.0,
    fuelMass: 6.0,
    avThrust1: 10,
    avThrust2: 0,
    burnTime1: 0.25,
    totalBurnTime: 0.26,
    delayTime: 0,
    isBooster: true,
  },
  {
    id: 'A8-3',
    name: 'A8-3',
    manufacturer: 'Estes',
    classLetter: 'A',
    width: 18,
    length: 70,
    mass: 16.0,
    fuelMass: 6.0,
    avThrust1: 10,
    avThrust2: 0,
    burnTime1: 0.25,
    totalBurnTime: 0.26,
    delayTime: 3.0,
    isBooster: false,
  },
  {
    id: 'A8-5',
    name: 'A8-5',
    manufacturer: 'Estes',
    classLetter: 'A',
    width: 18,
    length: 70,
    mass: 16.0,
    fuelMass: 6.0,
    avThrust1: 10,
    avThrust2: 0,
    burnTime1: 0.25,
    totalBurnTime: 0.26,
    delayTime: 5.0,
    isBooster: false,
  },
  {
    id: 'B6-0',
    name: 'B6-0',
    manufacturer: 'Estes',
    classLetter: 'B',
    width: 18,
    length: 70,
    mass: 19.0,
    fuelMass: 9.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 0.85,
    delayTime: 0,
    isBooster: true,
  },
  {
    id: 'B6-2',
    name: 'B6-2',
    manufacturer: 'Estes',
    classLetter: 'B',
    width: 18,
    length: 70,
    mass: 19.0,
    fuelMass: 9.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 0.85,
    delayTime: 2.0,
    isBooster: false,
  },
  {
    id: 'B6-4',
    name: 'B6-4',
    manufacturer: 'Estes',
    classLetter: 'B',
    width: 18,
    length: 70,
    mass: 19.0,
    fuelMass: 9.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 0.85,
    delayTime: 4.0,
    isBooster: false,
  },
  {
    id: 'B6-6',
    name: 'B6-6',
    manufacturer: 'Estes',
    classLetter: 'B',
    width: 18,
    length: 70,
    mass: 19.0,
    fuelMass: 9.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 0.85,
    delayTime: 6.0,
    isBooster: false,
  },
  {
    id: 'C6-0',
    name: 'C6-0',
    manufacturer: 'Estes',
    classLetter: 'C',
    width: 18,
    length: 70,
    mass: 25.0,
    fuelMass: 19.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 1.7,
    delayTime: 0,
    isBooster: true,
  },
  {
    id: 'C6-3',
    name: 'C6-3',
    manufacturer: 'Estes',
    classLetter: 'C',
    width: 18,
    length: 70,
    mass: 25.0,
    fuelMass: 19.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 1.7,
    delayTime: 3.0,
    isBooster: false,
  },
  {
    id: 'C6-5',
    name: 'C6-5',
    manufacturer: 'Estes',
    classLetter: 'C',
    width: 18,
    length: 70,
    mass: 25.0,
    fuelMass: 19.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 1.7,
    delayTime: 5.0,
    isBooster: false,
  },
  {
    id: 'C6-7',
    name: 'C6-7',
    manufacturer: 'Estes',
    classLetter: 'C',
    width: 18,
    length: 70,
    mass: 25.0,
    fuelMass: 19.0,
    avThrust1: 25,
    avThrust2: 6,
    burnTime1: 0.4,
    totalBurnTime: 1.7,
    delayTime: 7.0,
    isBooster: false,
  },
  {
    id: 'D12-0',
    name: 'D12-0',
    manufacturer: 'Estes',
    classLetter: 'D',
    width: 24,
    length: 70,
    mass: 45.0,
    fuelMass: 25.0,
    avThrust1: 24,
    avThrust2: 10,
    burnTime1: 0.6,
    totalBurnTime: 1.75,
    delayTime: 0,
    isBooster: true,
  },
  {
    id: 'D12-3',
    name: 'D12-3',
    manufacturer: 'Estes',
    classLetter: 'D',
    width: 24,
    length: 70,
    mass: 45.0,
    fuelMass: 25.0,
    avThrust1: 24,
    avThrust2: 10,
    burnTime1: 0.6,
    totalBurnTime: 1.75,
    delayTime: 3.0,
    isBooster: false,
  },
  {
    id: 'D12-5',
    name: 'D12-5',
    manufacturer: 'Estes',
    classLetter: 'D',
    width: 24,
    length: 70,
    mass: 45.0,
    fuelMass: 25.0,
    avThrust1: 24,
    avThrust2: 10,
    burnTime1: 0.6,
    totalBurnTime: 1.75,
    delayTime: 5.0,
    isBooster: false,
  },
  {
    id: 'D12-7',
    name: 'D12-7',
    manufacturer: 'Estes',
    classLetter: 'D',
    width: 24,
    length: 70,
    mass: 45.0,
    fuelMass: 25.0,
    avThrust1: 24,
    avThrust2: 10,
    burnTime1: 0.6,
    totalBurnTime: 1.75,
    delayTime: 7.0,
    isBooster: false,
  },
  {
    id: 'E9-4',
    name: 'E9-4',
    manufacturer: 'Estes',
    classLetter: 'E',
    width: 24,
    length: 95,
    mass: 38.0,
    fuelMass: 17.0,
    avThrust1: 28,
    avThrust2: 9,
    burnTime1: 0.5,
    totalBurnTime: 3.3,
    delayTime: 4.0,
    isBooster: false,
  },
  {
    id: 'E9-6',
    name: 'E9-6',
    manufacturer: 'Estes',
    classLetter: 'E',
    width: 24,
    length: 95,
    mass: 38.0,
    fuelMass: 17.0,
    avThrust1: 28,
    avThrust2: 9,
    burnTime1: 0.5,
    totalBurnTime: 3.3,
    delayTime: 6.0,
    isBooster: false,
  },
  {
    id: 'E9-8',
    name: 'E9-8',
    manufacturer: 'Estes',
    classLetter: 'E',
    width: 24,
    length: 95,
    mass: 38.0,
    fuelMass: 17.0,
    avThrust1: 28,
    avThrust2: 9,
    burnTime1: 0.5,
    totalBurnTime: 3.3,
    delayTime: 8.0,
    isBooster: false,
  },
  {
    id: 'E12-4',
    name: 'E12-4',
    manufacturer: 'Estes',
    classLetter: 'E',
    width: 24,
    length: 113,
    mass: 57.7,
    fuelMass: 35.4,
    avThrust1: 32,
    avThrust2: 11,
    burnTime1: 0.6,
    totalBurnTime: 2.7,
    delayTime: 4.0,
    isBooster: false,
  },
  {
    id: 'E12-6',
    name: 'E12-6',
    manufacturer: 'Estes',
    classLetter: 'E',
    width: 24,
    length: 113,
    mass: 57.7,
    fuelMass: 35.4,
    avThrust1: 32,
    avThrust2: 11,
    burnTime1: 0.6,
    totalBurnTime: 2.7,
    delayTime: 6.0,
    isBooster: false,
  },
  {
    id: 'F15-0',
    name: 'F15-0',
    manufacturer: 'Estes',
    classLetter: 'F',
    width: 29,
    length: 113,
    mass: 73.0,
    fuelMass: 60.0,
    avThrust1: 50,
    avThrust2: 11,
    burnTime1: 0.5,
    totalBurnTime: 3.45,
    delayTime: 0,
    isBooster: true,
  },
  {
    id: 'F15-4',
    name: 'F15-4',
    manufacturer: 'Estes',
    classLetter: 'F',
    width: 29,
    length: 113,
    mass: 73.0,
    fuelMass: 60.0,
    avThrust1: 50,
    avThrust2: 11,
    burnTime1: 0.5,
    totalBurnTime: 3.45,
    delayTime: 4.0,
    isBooster: false,
  },
  {
    id: 'F15-6',
    name: 'F15-6',
    manufacturer: 'Estes',
    classLetter: 'F',
    width: 29,
    length: 113,
    mass: 73.0,
    fuelMass: 60.0,
    avThrust1: 50,
    avThrust2: 11,
    burnTime1: 0.5,
    totalBurnTime: 3.45,
    delayTime: 6.0,
    isBooster: false,
  },
  {
    id: 'F15-8',
    name: 'F15-8',
    manufacturer: 'Estes',
    classLetter: 'F',
    width: 29,
    length: 113,
    mass: 73.0,
    fuelMass: 60.0,
    avThrust1: 50,
    avThrust2: 11,
    burnTime1: 0.5,
    totalBurnTime: 3.45,
    delayTime: 8.0,
    isBooster: false,
  },
];

export const ENGINES_BY_ID: Record<string, Engine> = Object.fromEntries(
  ENGINES.map((e) => [e.id, e]),
);

export function getEngine(id: string): Engine {
  const e = ENGINES_BY_ID[id];
  if (!e) throw new Error(`Unknown engine id: ${id}`);
  return e;
}

export function enginesForStage(opts: {
  bodyDiameterCm: number;
  isBoosterStage: boolean;
}): Engine[] {
  const bodyDiameterMm = opts.bodyDiameterCm * 10;
  return ENGINES.filter(
    (e) => e.isBooster === opts.isBoosterStage && bodyDiameterMm >= e.width + 1,
  );
}
